### ISSUE TITLE
Build a full HPO CodeSystem

### ISSUE THREAD

**Issue by ShahimEssaid** [phenopackets/core-ig#10]
We need a full CodeSystem for HPO.

**Comment by ShahimEssaid** [comment]
https://www.hl7.org/fhir/codesystem.html

**Comment by iimpulse** [comment]
Tracking software work...

https://github.com/monarch-initiative/phenol/issues/310

**Comment by ShahimEssaid** [comment]
@iimpulse the canonical resource concept is relevant for the URL of the CodeSystem and other canonical resources:

https://www.hl7.org/fhir/resource.html#canonical
https://www.hl7.org/fhir/references.html#canonical

We can discuss this later after you have some content to text.

**Comment by ShahimEssaid** [comment]
It might be a good idea to generate this content with the HAPI libraries to make sure the generated CodeSystem is valid, and to help with evolving it in the future. The HAPI model libraries make it easy to generate valid FHIR serializations and also has migration support for future FHIR versions. I can help with the Maven project setup if needed but you can also see the "parent" project under the /projects folder for a good starting point.

**Comment by pnrobinson** [comment]
Here is code to build a full HPO Code System etc. 
https://github.com/monarch-initiative/pyrophen
We still need to figure out the best way of integration with this IG.
