### ISSUE TITLE
Use HL7 ValueSet or CodeSystem wherever possible

### ISSUE THREAD

**Issue by ShahimEssaid** [phenopackets/core-ig#12]
I'm in favor of reusing codes from the FHIR specification wherever possible as long as it doesn't interfere with the meaning being captured by the resource instances. This will facilitate interoperability.

We have one good example where we can consider this.  In the current phenotypic abnormality profile we use a value set for the components of the Observation. The ValueSet for the components right now is based on parent HPO concepts but there are HL7 alternatives for this.

Our current component ValueSet: http://phenopackets.org/core-ig/master/ValueSet-phenotypic-component.html

Notice that we have one code for onset, and it is used for fixed slicing here: https://github.com/phenopackets/core-ig/blob/e28a5cc866811f00b12af9bc7dba00c843d5b2f1/ig-root/input/resources/StructureDefinition-observation-phenotypic-abnormality.xml#L133 and here: https://github.com/phenopackets/core-ig/blob/e28a5cc866811f00b12af9bc7dba00c843d5b2f1/ig-root/input/resources/StructureDefinition-observation-phenotypic-abnormality.xml#L159

HL7 based codes: http://hl7.org/fhir/R4/v3/ActCode/cs.html#v3-ActCode-_LOINCObservationActContextAgeType

There is a ValueSet based on the above CodeSystem but it has too many codes. We can define our custom ValueSet based on the above HL7 CodeSystem. The existing FHIR ValueSet is: http://hl7.org/fhir/R4/v3/ObservationType/vs.html and the age entries start at: http://hl7.org/fhir/R4/v3/ObservationType/vs.html#http---terminology.hl7.org-CodeSystem-v3-ActCode-21611-9

I'm +1 for migrating our code for indicating the age component to the above HL7 based codes. This means that we'll have a code in our custom value set for the code: http://hl7.org/fhir/R4/v3/ActCode/cs.html#v3-ActCode-30525-0

The parent abstract concept is: http://hl7.org/fhir/R4/v3/ActCode/cs.html#v3-ActCode-_LOINCObservationActContextAgeType

We'll gradually find additional codes for the other components. This doesn't interfere with using HPO to capture the clinical meaning. This is more about defining components that are tagged with HL7 codes as much as possible instead of inventing our own codes.

**Comment by ShahimEssaid** [comment]
This doesn't mean that we should have only that code in our value set. If there is a strong preference to also be able to have the HPO "onset" codes as the component marker, we can also add the HPO code to the profile as another option to "markup" the onset component but there isn't really a good reason to have multiple options in this case. This codes is basically a mapping of the PP onset field name. It doesn't have anything to do with the value captured in that component.

**Comment by ShahimEssaid** [comment]
Severity: http://hl7.org/fhir/R4/v3/ObservationValue/cs.html#v3-ObservationValue-_SeverityObservation

**Comment by pnrobinson** [comment]
this issue has become stale, closing.
