### ISSUE TITLE
KaryotypicSex CodeSystem

### ISSUE THREAD

**Issue by pnrobinson** [phenopackets/core-ig#13]
I think that we do not want to make this be ordinal as in the instructional video by @ShahimEssaid 
The fact that KaryotypicSex uses an ordinal field in the protobuf version is an implementation detail -- it needs to be done like this in protobuf. However, the semantics of the field are categorical.

Can we implement this as follows?  
```
 "title": "KaryotypicSex CodeSystem",
  "property": [
    {
      "code": "categorical",
      "description": "The specific type of karyotypic sex",
      "type": "string"
    }
  ],
```
with the concepts being defined as
```
 {
      "code": "UNKNOWN_KARYOTYPE",
      "display": "unknown karyotype",
      "definition": "Untyped or inconclusive karyotyping",
      "property": [
        {
          "code": "categorical",
          "valueString": "UNKNOWN_KARYOTYPE"
        }
      ]
    },
```

**Comment by ShahimEssaid** [comment]
Yes, I agree, those videos are not about the IG for this project. They are just to demonstrate the idea of how to represent a code system. There is no karyotypic sex representation in our core ig so far.

What is the property "categorical" used for? the codes itself is holding the same value as in your example of "categorical" usage. We can use properties to capture any metadata or relationships between the concepts as needed.

**Comment by pnrobinson** [comment]
In general, the results of a test can be numeric, ordinal (having some natural order from low to high), or categorical (different categories that do not have a natural ordering). LOINC codes largely have one of these three categories. I take it from your answer that this is not how things are represented in FHIR, though.

**Comment by ShahimEssaid** [comment]
I think there are two issues here. There is the concept, meaning, entity, etc. and there is the issue of having or creating some string or value to stand for that concept in some concrete serialization of information that needs to refer to that concept. So, for HOP as an example, there are values that are the identifiers/identity of the concepts in HPO but the same concepts have other identifiers in other terminologies.

The FHIR CodeSystem representation has concept.code for the identifier, .display for a label, .definition for that, etc.  All this is based on what the ontology, terminology, knowledge graph, etc. says those valuse should be. FHIR doesn't specify much about that other than the values need to fit the data types for those fields. Any additional knowledge about the concepts that needs to be also captured in a CodeSystem (as opposed to in it's native representation format) needs to be modeled with properties.  FHIR also allows or a tree organization of concepts. I still need to follow up on what was said on the FHIR chat thread about this. Haven't looked there yet.

Going back to the result of a karyotypic sex from a lab. If there isn't already a good encoding of this out there in some well established terminology, we should create our own code system for this until we find better options. Whether a lab uses any of these values (our code system or some other one) is not an issue unless most labs do the same thing. The raw data out of a lab will then need to be mapped to our code system choices.  Labs, at some point, can then choose to add an additional coding of their results according to our code system. CodeableConcept allows for multiple Coding entries the same concept, one Coding per code system.
