### ISSUE TITLE
Advantages and disadvantages of extensions

### ISSUE THREAD

**Issue by pnrobinson** [phenopackets/core-ig#27]
Many of the elements in the GA4GH Phenopacket, such as 'Severity' (see PhenotypicFeature--https://phenopacket-schema.readthedocs.io/en/latest/phenotype.html) are not really essential for downstream use. Therefore, maybe it is not worth the burden on downstream implementers to add an extension to this IG to represent these elements.

Should we try to write an IG that does not use any extension at all?

Thoughts?

**Comment by jmandel** [comment]
Avoiding extensions in itself is not a great goal. Trivially, you can avoid extensions by putting data in "not quite semantically correct" existing elements or making liberal use of tags, components, references, and other areas of flexibility -- but these approaches can cause confusion and inconsistency.

If you understand your use case and certain data really aren't needed for it (but are nice to have), you might leave the exercise of modeling such data for a subsequently release. But don't make the decision based on whether you need to declare an extension or not; decide based on your requirements.

**Comment by ametke** [comment]
I agree with @jmandel and I think this has to be looked at on a case by case basis. That said, some of the extensions that I created on the initial Phenopackets IG could have been represented nicely as component observations.

**Comment by pnrobinson** [comment]
thanks for the input/advice!
