### ISSUE TITLE
update link

### ISSUE THREAD

**Issue by pnrobinson** [phenopackets/core-ig#30]
http://phenopackets.org/core-ig/

@julesjacobsen please update the link on the start page -- thanks to @ametke we are now building to github io!
PS -- could I get admin rights?

**Comment by julesjacobsen** [comment]
What link where?! Do you mean *all* the links from the phenopacket-schema repo?

**Comment by pnrobinson** [comment]
The link on the main page of this repo under "About" should point to http://phenopackets.org/core-ig/ -- the current address is wrong and gives a 404

**Comment by julesjacobsen** [comment]
I've changed it, but you do have the permissions to do this.
